#!/usr/bin/env python

import socket
import struct
from os import environ as env

import lightCommon as lc
import HTMLHelper as html


print(html.textHeader())

lightsOn=[]

allLights = lc.enumerateAll()

for node,props in allLights:

    if props[lc.l_stat] == lc.on:
        lightsOn.append((node,props[lc.l_num],props[lc.l_name]))

if len(lightsOn) > 0:
    html.printl('Turning on: ')

for light in lightsOn:        
    lightNum = light[1]
    lightName = light[2]
    lightStatus = lc.msg_off
    node = light[0]

    rc = lc.sendSetMsg(node,lightNum,lightStatus)
    html.printl(str(lightName))


html.printl('All lights off')

print(html.textFooter())
