#!/usr/bin/env python

import socket
import struct
from os import environ as env

import lightCommon as lc
import HTMLHelper as html

print(html.textHeader())

lights_off=[]

all_lights = lc.enumerateAll()

for node,props in all_lights:

    if props[lc.l_stat] == lc.off:
        lights_off.append((node,props[lc.l_num],props[lc.l_name]))

if len(lights_off) > 0:
    html.printl('Turning on: ')

for light in lights_off:        
    light_num = light[1]
    light_name = light[2]
    light_status = lc.msg_on
    node = light[0]

    rc = lc.sendSetMsg(node,light_num,light_status)
    html.printl(str(light_name))


html.printl('All lights on')

print(html.textFooter())
