#!/usr/bin/env python

import socket
import struct
from os import environ as env

import lightCommon as lc
import HTMLHelper as html


if '__main__':

    # Print the HTML that says this is just text
    print(html.textHeader())

    # Query string parser
    queryArg=html.queryStringParser(env.get('QUERY_STRING'))

    #html.printl(str(queryArg))
      
    # Send msg_req for every item in the query string
    reqType = lc.msg_set
    for item in queryArg:

        node = item.split('=')[0]
        item = item.split('=')[1]
        lightNum = item.split('%2C')[0]
        lightStatus = item.split('%2C')[1]
        
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.connect((node, lc.port()))
        s.sendall(struct.pack(lc.packString,reqType,int(lightNum),int(lightStatus)))
        s.close()

        lightName = lc.lightList[node][lc.l_name]

        if ( int(lightStatus) == lc.msg_on ):
            html.printl(lightName + ' turned on')
        else:
            html.printl(lightName + ' turned off')

    print(html.textFooter())
