#!/usr/bin/env python

import socket
import struct
from os import environ as env

import lightCommon as lc
import HTMLHelper as html


# Print the HTML that says this is just text
print(html.textHeader())

node_list = lc.enumerateAll()

for node,props in node_list:

    if ( int(props[lc.l_stat]) == lc.on ):
        html.printl(props[lc.l_name] + ' is on')
    else:
        #html.printl(props[lc.l_name] + ' is off')
        pass

print(html.textFooter())

