#!/usr/bin/env python

import socket
import struct
from os import environ as env

import lightCommon as lc
import HTMLHelper as html


# Print the HTML that says this is just text
print(html.textHeader())

nodeList = lc.enumerateAll()

for node,props in nodeList:

    if ( int(props[lc.l_stat]) == lc.msg_on ):
        html.printl(props[lc.l_name] + ' is on')
    else:
        html.printl(props[lc.l_name] + ' is off')

print(html.textFooter())

