#!/usr/bin/env python

import socket
import struct
from os import environ as env

import lightCommon as lc
import HTMLHelper as html


# Print the HTML that says this is just text
print(html.textHeader())

# Query string parser
query_arg=html.queryStringParser(env.get('QUERY_STRING'))

print '<!-- Query String = ' + env.get('QUERY_STRING') + '-->'
print '<!-- Query Args = ' + str(query_arg) + '-->'
# Send msg_req for every item in the query string
for item in query_arg:

    try:
        node = item.split('=')[0]
        item = item.split('=')[1]
        light_num = int(item.split('%2C')[0])
        light_status = int(item.split('%2C')[1])
        light_time = int(item.split('%2C')[2])

        # return code
        rc = lc.sendSetMsg(node,light_num,light_status,light_time)

        light_name = lc.lightList[node][light_num][lc.l_name]

        if ( light_status == lc.on ):
            html.printl(str(light_name) + ' will turn on ' + str(light_time) + ' seconds in the future')
        else:
            html.printl(str(light_name) + ' will turn off ' + str(light_time) + ' seconds in the future')

    except KeyError as e:
        html.printl('Key Error: ' + str(e))

    except IndexError as e:
        html.printl('Index Error: ' + str(e))

print(html.textFooter())
